name: chess_trainer
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  chess: ^0.8.1
  chessground: ^7.2.0
  dartchess: ^0.11.1
  flutter:
    sdk: flutter
  multistockfish: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

dependency_overrides:
  characters: ^1.4.1
  material_color_utilities: ^0.13.0
  meta: ^1.17.0
  test_api: ^0.7.7
  fast_immutable_collections: ^11.0.4
  chess: ^0.8.1

flutter:
  uses-material-design: true
